[pytest]
addopts = 
    -ra
    -q
    -v 
   # --slowmo 500
    --html=report.html

testpaths =  tests/test_addingitem.py
    tests/test_removingAnitem.py
    tests/test_addingmultipleitem.py
    tests/test_Checkout.py
    
markers = order
    


#multiple ways to run your tests in order
#1. pytst-ordering 
#mark you orders with @pytest.mark.order(1)
## do it for class,function or fucntions in class BUT in one file with order 1,2,3... dont use it in multiple accross file with order 1,2,3 

#2. In pytest.ini -> mention in testpath sequencely 
#testpath = tests/test_addingitem.py
#           tests/test_addingmultiple.py

#3. In conftest.py  -> Create a test_suite.py that imports and sequences everything explicitly

# test_suite.py
#from test_login import TestLogin
#from test_addingitem import TestAddItem
#from test_removingitem import TestRemoveItem
#from test_checkout import TestCheckout

#then run the suite -> python -m pytest tests/test_suite.py -v


#4. Run directly in terminal 
#python -m pytest tests/test_login.py \
#                 tests/test_addingitem.py \
#                 tests/test_removingitem.py \
#                 tests/test_checkout.py -v


# Option 1 + Option 2 when 1 test depends on another