# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestRemovingAnitem():
  def test_removingAnitem(self,browser_open):
    self.browser_open = browser_open
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]").click()
    value = self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"cart-list\"]").get_attribute("value")
    assert value == "None"
    self.browser_open.find_element(By.ID, "react-burger-menu-btn").click()
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-sidebar-link\"]").click()
  
