# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRemovingAnitem():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_removingAnitem(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.set_window_size(1190, 764)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]").click()
    value = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"cart-list\"]").get_attribute("value")
    assert value == "None"
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-sidebar-link\"]").click()
  
