# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddingitem():
  def test_addingitem(self,browser_open):
    self.browser_open = browser_open
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-sauce-labs-backpack-img\"]").click()
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    assert self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item\"]").text == "Sauce Labs Backpack"
    self.drbrowser_openiver.find_element(By.ID, "react-burger-menu-btn").click()
    self.browser_open.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-sidebar-link\"]").click()
  
